# Generated by Django 3.1.1 on 2020-09-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('contenido', models.TextField(blank=True)),
                ('fecha_creación', models.DateField(default='2020-09-21')),
                ('categoría', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='todoapp.categoria')),
            ],
        ),
    ]
