# Generated by Django 3.1.1 on 2020-09-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tarea',
        ),
    ]
