# Generated by Django 3.1.1 on 2020-09-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20200922_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='categoría',
            new_name='categoria',
        ),
    ]
