# Generated by Django 3.1.1 on 2020-09-23 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('todoapp', '0004_auto_20200922_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='categoria',
            field=models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creación',
            field=models.DateField(default='2020-09-23'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
